# Generated by Django 5.1 on 2024-10-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_disease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
