# Generated by Django 5.1 on 2024-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0004_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.JSONField(default=list),
        ),
    ]
