# Generated by Django 5.1 on 2024-10-25 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0011_remove_chatmessage_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_app.user')),
            ],
        ),
    ]
